[package]
name = "hrc"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
space = { version = "0.11.0", default-features = false }
bitvec = { version = "0.22.3", default-features = false, features = ["alloc"] }
itertools = { version = "0.10.0", default-features = false }

[dev-dependencies]
rand = "0.8.3"
rand_xoshiro = "0.6.0"
itertools = { version = "0.10.0" }
