[package]
name = "hrc"
version = "0.1.0"
edition = "2018"
resolver = "2"

[features]
default = ["stats"]

stats = []

[dependencies]
space = { version = "0.11.0", default-features = false, features = ["simd-hamming"] }
bitvec = { version = "0.22.3", default-features = false, features = ["alloc"] }
itertools = { version = "0.10.0", default-features = false }
smallvec = { version = "1.6.1", default-features = false }

[dev-dependencies]
rand = "0.8.3"
rand_xoshiro = "0.6.0"
itertools = { version = "0.10.0" }
csv = "1.1.6"
serde = { version = "1.0.126", features = ["derive"] }
