[package]
name = "hrc"
version = "0.1.0"
edition = "2018"
resolver = "2"

[features]
default = ["stats"]

stats = []

[dependencies]
space = { version = "0.12.0", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
header-vec = { git = "https://github.com/vadixidav/header-vec.git", default-features = false }

[dev-dependencies]
space = { version = "0.12.0", default-features = false, features = ["simd-hamming"] }
rand = "0.8.4"
rand_xoshiro = "0.6.0"
csv = "1.1.6"
serde = { version = "1.0.126", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
